services:
  mqtt-worker:
    container_name: mqtt-worker
    hostname: 
    build:
      context: ./mqtt-worker
    restart: always
    env_file:
      - .env
    ports:
      - ${MQTT_WORKER_PORT}:${MQTT_WORKER_PORT}
    environment:
      - MQTT_IP=${MQTT_IP}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
  redis-db:
    container_name: redis-db
    image: redis:alpine
    # --save = redis will not save data to disk
    # --appendonly no = disables Append-Only files, no saves are persistant
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    tmpfs:
      - /data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
