"""db änderungen implementiert

Revision ID: 8f5f56beaca0
Revises: d12efd75607f
Create Date: 2025-11-26 21:52:19.639695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5f56beaca0'
down_revision: Union[str, Sequence[str], None] = 'd12efd75607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'penalty')
    op.drop_column('attempts', 'duration')
    op.drop_column('attempts', 'max_speed')
    op.add_column('challenges', sa.Column('esp_mac', sa.String(), nullable=True))
    op.add_column('leaderboards', sa.Column('best_score', sa.Float(), nullable=True))
    op.drop_column('leaderboards', 'total_points')
    op.add_column('scores', sa.Column('attempt_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('scores_run_id_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'attempts', ['attempt_id'], ['id'])
    op.drop_column('scores', 'run_id')
    op.add_column('teams', sa.Column('rfid_identifier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kc_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['kc_id'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'kc_id')
    op.drop_column('teams', 'rfid_identifier')
    op.add_column('scores', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_run_id_fkey'), 'scores', 'attempts', ['run_id'], ['id'])
    op.drop_column('scores', 'attempt_id')
    op.add_column('leaderboards', sa.Column('total_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('leaderboards', 'best_score')
    op.drop_column('challenges', 'esp_mac')
    op.add_column('attempts', sa.Column('max_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attempts', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attempts', sa.Column('penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
