"""db änderungen implementiert2

Revision ID: e59a9185786e
Revises: 8f5f56beaca0
Create Date: 2025-11-26 21:53:19.097270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59a9185786e'
down_revision: Union[str, Sequence[str], None] = '8f5f56beaca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('penalty_amount', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('Strecke_Verlassen', name='penaltytype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalties')
    # ### end Alembic commands ###
