events {}

http {
    upstream user_service {
        server user-service:8001;
    }

    upstream auth_service {
        server auth-service:8002;
    }

    upstream challenge_service {
        server challenge-service:8003;
    }

    upstream attempt_service {
        server attempt-service:8004;
    }

    upstream score_service {
        server score-service:8005;
    }

    upstream team_service {
        server team-service:8006;
    }

    server {
        listen 80;
        client_max_body_size 100M;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;

        location = /_auth {
            internal;
            proxy_pass http://auth_service/api/auth/verify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

        location = /internal/ {
            internal;
            proxy_pass http://auth_service/api/auth/internal;
        }

        location /login {
            proxy_pass http://auth_service/api/auth/login;
        }

        location /refresh {
            proxy_pass http://auth_service/api/auth/refresh;
        }

        location ~ ^/users(/.*)?$ {
            auth_request /_auth;
            proxy_pass http://user_service/api/users$1$is_args$args;
        }

        location ~ ^/teams(/.*)?$ {
            auth_request /_auth;
            proxy_pass http://team_service/api/teams$1$is_args$args;
        }

        location ~ ^/drivers(/.*)?$ {
            auth_request /_auth;
            proxy_pass http://team_service/api/drivers$1$is_args$args;
        }

        location ~ ^/attempts(/.*)?$ {
            auth_request /_auth;
            proxy_pass http://attempt_service/api/attempts$1$is_args$args;
        }

        location ~ ^/challenges(/.*)?$ {
            auth_request /_auth;
            proxy_pass http://challenge_service/api/challenges$1$is_args$args;
        }

        location ~ ^/leaderboard(/.*)?$ {
            proxy_pass http://score_service/api/leaderboard$1$is_args$args;
        }

        location ~ ^/scores(/.*)?$ {
            auth_request /_auth;
            proxy_pass http://score_service/api/scores$1$is_args$args;
        }
    }
}