events {}

http {
    upstream user_service {
        server user-service:8001;
    }

    upstream auth_service {
        server auth-service:8002;
    }

    upstream challenge_service {
        server challenge-service:8003;
    }

    upstream attempt_service {
        server attempt-service:8004;
    }

    upstream score_service {
        server score-service:8005;
    }

    upstream team_service {
        server team-service:8006;
    }

    server {
        listen 80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;

        location = /_auth {
            internal;
            proxy_pass http://auth_service/api/auth/verify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        location /login {
            proxy_pass http://auth_service/api/auth/login;
        }

        location /users/ {
            auth_request /_auth;
            rewrite ^/users/?(.*)$ /$1 break;
            proxy_pass http://user_service/api/auth/;
        }

        location /teams/ {
            auth_request /_auth;
            rewrite ^/api/teams/?(.*)$ /$1 break; 
            proxy_pass http://team_service/api/teams/;
        }

        location /attempts/ {
            auth_request /_auth;
            rewrite ^/attempts/?(.*)$ /$1 break;
            proxy_pass http://attempt_service/api/attempts/;
        }

        location /challenges/ {
            auth_request /_auth;
            rewrite ^/challenges/?(.*)$ /$1 break;
            proxy_pass http://challenge_service/api/challenges/;
        }

        location ~ ^/leaderboard(/.*)?$ {
            auth_request off;
            rewrite ^/leaderboard/?(.*)$ /api/leaderboard/$1 break;
            proxy_pass http://score_service;
        }

        location /scores/ {
            auth_request /_auth;
            rewrite ^/scores/?(.*)$ /$1 break;
            proxy_pass http://score_service/api/scores/;
        }
    }
}